package main

import (
	"bytes"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"embed"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"io"
	"log"
	"math/big"
	"net/http"
	"os"
	"os/exec"
	"regexp"
	"sort"
	"strings"
	"text/template"
	"time"
)

//go:embed manifests/*.yaml
var manifestFS embed.FS

// TemplateConfig holds all template variables for manifest rendering
type TemplateConfig struct {
	Namespace             string
	Domain                string
	DomainUpper           string // e.g. CMARS.COM
	DomainNetBIOS         string // e.g. CMARS
	AdminPassword         string // legacy (backward compat)
	ConsoleAdminPassword  string // Keycloak admin password
	OrgName               string
	PostgresPassword      string
	ConsoleDomain         string // e.g. console.cmars.com
	AuthDomain            string // e.g. auth.cmars.com
	MailDomain            string // e.g. mail.cmars.com
	PortalDomain          string // e.g. portal.cmars.com
	AppEngineDomain       string // e.g. apps.cmars.com
	DomainDC              string // e.g. DC=cmars,DC=com
	TLSCertBase64         string // base64-encoded TLS certificate
	TLSKeyBase64          string // base64-encoded TLS private key

	// Per-service passwords (generated by Operator)
	DCAdminPassword       string // Samba DC admin (= user input AdminPassword)
	DBPassword            string // PostgreSQL polyon user
	KCAdminPassword       string // Keycloak bootstrap admin
	StalwartAdminPassword string // Stalwart fallback admin
	RustFSSecretKey       string // RustFS secret key
	LiteLLMMasterKey      string // LiteLLM AI Gateway master key
	GiteaAdminPassword    string // Gitea admin password
	AppEngineVersion           string // e.g. "v0.5.6"
	DCVersion                  string // e.g. "v1.0.0"
	MailVersion                string // e.g. "v1.0.0"
	CoreVersion                string // e.g. "v1.14.2"
	ConsoleVersion             string // e.g. "v1.10.16"
	PortalVersion              string // e.g. "v0.2.0"
	AppEngineClientSecret      string // Keycloak polyon-appengine client secret (set during provisioning)
	AppEngineAdminClientSecret string // Keycloak polyon-appengine-admin client secret (admin realm)
}

// generatePassword creates a random alphanumeric password of given length
func generatePassword(length int) string {
	const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	b := make([]byte, length)
	rand.Read(b)
	for i := range b {
		b[i] = charset[int(b[i])%len(charset)]
	}
	return string(b)
}

// DomainToDC converts a domain like "cmars.com" to "DC=cmars,DC=com"
// readVersions reads VERSION file and returns a key→value map (fallback defaults).
func readVersions() map[string]string {
	defaults := map[string]string{
		"core": "1.14.2", "console": "1.10.16", "portal": "0.2.0",
		"operator": "0.7.9", "dc": "1.0.1", "mail": "1.0.0",
		"appengine": "0.5.6", "chat": "1.0.0", "drive": "1.0.0",
	}
	data, err := os.ReadFile("VERSION")
	if err != nil {
		return defaults
	}
	for _, line := range strings.Split(string(data), "\n") {
		parts := strings.SplitN(strings.TrimSpace(line), "=", 2)
		if len(parts) == 2 {
			defaults[parts[0]] = parts[1]
		}
	}
	return defaults
}

// fetchLatestTag queries Docker Hub for the latest vX.Y.Z tag of a jupitertriangles image.
// Falls back to fallbackVersion if unavailable or no network.
func fetchLatestTag(image, fallbackVersion string) string {
	url := fmt.Sprintf("https://hub.docker.com/v2/repositories/jupitertriangles/%s/tags/?page_size=25&ordering=last_updated", image)
	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		log.Printf("[version] Docker Hub API 실패 (%s): %v — fallback: v%s", image, err, fallbackVersion)
		return "v" + fallbackVersion
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)

	var result struct {
		Results []struct {
			Name string `json:"name"`
		} `json:"results"`
	}
	if err := json.Unmarshal(body, &result); err != nil {
		return "v" + fallbackVersion
	}

	// vX.Y.Z 패턴만 추출 후 semver 정렬
	re := regexp.MustCompile(`^v(\d+)\.(\d+)\.(\d+)$`)
	var tags []string
	for _, r := range result.Results {
		if re.MatchString(r.Name) {
			tags = append(tags, r.Name)
		}
	}
	if len(tags) == 0 {
		return "v" + fallbackVersion
	}
	sort.Slice(tags, func(i, j int) bool {
		// 문자열 semver 정렬: 자리수 같으면 lexicographic이 semver와 동일
		return tags[i] > tags[j]
	})
	log.Printf("[version] %s 최신 태그: %s", image, tags[0])
	return tags[0]
}

// fetchRecentTags queries Docker Hub for the N most recent vX.Y.Z tags of a repo.
// Falls back to current VERSION file value on any error.
func fetchRecentTags(repo string, n int) []string {
	fallback := readVersions()
	// derive image name from repo "jupitertriangles/polyon-xxx"
	parts := strings.SplitN(repo, "/", 2)
	imgName := parts[len(parts)-1] // e.g. "polyon-core"
	key := strings.TrimPrefix(imgName, "polyon-") // e.g. "core"
	fallbackVer := "v" + fallback[key]

	url := fmt.Sprintf("https://hub.docker.com/v2/repositories/%s/tags?page_size=%d&ordering=-last_updated", repo, n*5)
	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		log.Printf("[version] fetchRecentTags 실패 (%s): %v", repo, err)
		return []string{fallbackVer}
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)

	var result struct {
		Results []struct {
			Name string `json:"name"`
		} `json:"results"`
	}
	if err := json.Unmarshal(body, &result); err != nil {
		return []string{fallbackVer}
	}

	re := regexp.MustCompile(`^v(\d+)\.(\d+)\.(\d+)$`)
	var tags []string
	for _, r := range result.Results {
		if re.MatchString(r.Name) {
			tags = append(tags, r.Name)
		}
	}
	sort.Slice(tags, func(i, j int) bool { return tags[i] > tags[j] })
	if len(tags) == 0 {
		return []string{fallbackVer}
	}
	if len(tags) > n {
		tags = tags[:n]
	}
	return tags
}

// resolveVersions fetches latest tags from Docker Hub; falls back to VERSION file.
func resolveVersions() map[string]string {
	fallback := readVersions()
	images := map[string]string{
		"core": "core", "console": "console", "portal": "portal",
		"dc": "dc", "mail": "mail", "appengine": "appengine",
	}
	result := make(map[string]string)
	for key, img := range images {
		result[key] = fetchLatestTag("polyon-"+img, fallback[key])
	}
	return result
}

func DomainToDC(domain string) string {
	parts := strings.Split(strings.ToLower(domain), ".")
	dcs := make([]string, len(parts))
	for i, p := range parts {
		dcs[i] = "DC=" + p
	}
	return strings.Join(dcs, ",")
}

// NewTemplateConfig derives computed fields from SetupConfig
func NewTemplateConfig(cfg SetupConfig) TemplateConfig {
	versions := resolveVersions()
	domain := cfg.Domain
	domainUpper := strings.ToUpper(domain)

	// NetBIOS name: first part of domain, uppercased
	netbios := domainUpper
	if idx := strings.Index(netbios, "."); idx > 0 {
		netbios = netbios[:idx]
	}

	// Subdomain defaults
	consoleSub := cfg.Subdomains.Console
	if consoleSub == "" {
		consoleSub = "console"
	}
	authSub := cfg.Subdomains.Auth
	if authSub == "" {
		authSub = "auth"
	}
	mailSub := cfg.Subdomains.Mail
	if mailSub == "" {
		mailSub = "mail"
	}
	portalSub := cfg.Subdomains.Portal
	if portalSub == "" {
		portalSub = "portal"
	}
	appEngineSub := cfg.Subdomains.AppEngine
	if appEngineSub == "" {
		appEngineSub = "apps"
	}

	domainLower := strings.ToLower(domain)

	consoleAdminPw := cfg.ConsoleAdminPassword
	if consoleAdminPw == "" {
		consoleAdminPw = cfg.AdminPassword
	}

	// Read TLS certificate and key
	var tlsCertB64, tlsKeyB64 string
	if certData, err := os.ReadFile("/tls/tls.crt"); err == nil {
		tlsCertB64 = base64.StdEncoding.EncodeToString(certData)
	}
	if keyData, err := os.ReadFile("/tls/tls.key"); err == nil {
		tlsKeyB64 = base64.StdEncoding.EncodeToString(keyData)
	}

	return TemplateConfig{
		Namespace:               cfg.Namespace,
		Domain:                  domain,
		DomainUpper:             domainUpper,
		DomainNetBIOS:           netbios,
		AdminPassword:           cfg.AdminPassword, // legacy compat
		ConsoleAdminPassword:    consoleAdminPw,
		OrgName:                 cfg.OrgName,
		PostgresPassword:        generatePassword(24),
		ConsoleDomain:           consoleSub + "." + domainLower,
		AuthDomain:              authSub + "." + domainLower,
		MailDomain:              mailSub + "." + domainLower,
		PortalDomain:            portalSub + "." + domainLower,
		AppEngineDomain:         appEngineSub + "." + domainLower,
		DomainDC:                DomainToDC(domain),
		TLSCertBase64:           tlsCertB64,
		TLSKeyBase64:            tlsKeyB64,

		// Per-service passwords
		DCAdminPassword:       cfg.AdminPassword, // user input
		DBPassword:            generatePassword(24),
		KCAdminPassword:       generatePassword(24),
		StalwartAdminPassword: generatePassword(24),
		RustFSSecretKey:       generatePassword(24),
		LiteLLMMasterKey:      "sk-polyon-" + generatePassword(24),
		GiteaAdminPassword:    cfg.AdminPassword, // same as DC admin
		AppEngineVersion:      versions["appengine"],
		DCVersion:             versions["dc"],
		MailVersion:           versions["mail"],
		CoreVersion:           versions["core"],
		ConsoleVersion:        versions["console"],
		PortalVersion:         versions["portal"],
	}
}

// renderManifest parses and executes a Go text/template manifest file
func renderManifest(name string, cfg TemplateConfig) (string, error) {
	data, err := manifestFS.ReadFile("manifests/" + name)
	if err != nil {
		return "", fmt.Errorf("read manifest %s: %w", name, err)
	}

	tmpl, err := template.New(name).Parse(string(data))
	if err != nil {
		return "", fmt.Errorf("parse manifest %s: %w", name, err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("render manifest %s: %w", name, err)
	}

	return buf.String(), nil
}

// applyManifest pipes rendered YAML to kubectl apply -f -
func applyManifest(yaml string) error {
	cmd := exec.Command("kubectl", "apply", "-f", "-")
	cmd.Stdin = strings.NewReader(yaml)

	var stderr bytes.Buffer
	cmd.Stderr = &stderr

	out, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("kubectl apply: %s\n%s", stderr.String(), err)
	}

	log.Printf("[K8S] %s", strings.TrimSpace(string(out)))
	return nil
}

// waitForReady waits for pods matching the label selector to become Ready
func waitForReady(ns, labelSelector string, timeout time.Duration) error {
	timeoutStr := fmt.Sprintf("%.0fs", timeout.Seconds())

	cmd := exec.Command("kubectl", "wait",
		"--for=condition=ready", "pod",
		"-l", labelSelector,
		"-n", ns,
		"--timeout="+timeoutStr,
	)

	var stderr bytes.Buffer
	cmd.Stderr = &stderr

	out, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("kubectl wait (%s): %s\n%s", labelSelector, stderr.String(), err)
	}

	log.Printf("[K8S] %s", strings.TrimSpace(string(out)))
	return nil
}

// deployManifest is a convenience that renders + applies + waits
func deployManifest(manifestName, labelSelector string, cfg TemplateConfig, timeout time.Duration) error {
	yaml, err := renderManifest(manifestName, cfg)
	if err != nil {
		return err
	}

	if err := applyManifest(yaml); err != nil {
		return err
	}

	if labelSelector != "" {
		if err := waitForReady(cfg.Namespace, labelSelector, timeout); err != nil {
			return err
		}
	}

	return nil
}

// ensureNamespace creates the namespace if it doesn't exist
func ensureNamespace(cfg TemplateConfig) error {
	yaml, err := renderManifest("namespace.yaml", cfg)
	if err != nil {
		return err
	}
	return applyManifest(yaml)
}

// generateSelfSignedCert creates a wildcard self-signed certificate for *.domain
func generateSelfSignedCert(domain string) (certPEM, keyPEM []byte, err error) {
	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, fmt.Errorf("generate key: %w", err)
	}

	serial, _ := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))

	tmpl := &x509.Certificate{
		SerialNumber: serial,
		Subject: pkix.Name{
			CommonName:   "*." + domain,
			Organization: []string{"PolyON"},
		},
		NotBefore:   time.Now().Add(-1 * time.Hour),
		NotAfter:    time.Now().Add(10 * 365 * 24 * time.Hour), // 10년
		KeyUsage:    x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		DNSNames:    []string{"*." + domain, domain},
	}

	certDER, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &priv.PublicKey, priv)
	if err != nil {
		return nil, nil, fmt.Errorf("create certificate: %w", err)
	}

	var certBuf bytes.Buffer
	pem.Encode(&certBuf, &pem.Block{Type: "CERTIFICATE", Bytes: certDER})

	privDER, err := x509.MarshalECPrivateKey(priv)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal key: %w", err)
	}

	var keyBuf bytes.Buffer
	pem.Encode(&keyBuf, &pem.Block{Type: "EC PRIVATE KEY", Bytes: privDER})

	return certBuf.Bytes(), keyBuf.Bytes(), nil
}

// ensureTLSSecret creates the polyon-tls Secret with a self-signed wildcard cert
func ensureTLSSecret(cfg TemplateConfig) error {
	// Check if secret already exists
	checkCmd := exec.Command("kubectl", "get", "secret", "polyon-tls", "-n", cfg.Namespace, "--no-headers")
	if err := checkCmd.Run(); err == nil {
		log.Printf("[K8S] polyon-tls secret already exists in %s", cfg.Namespace)
		return nil
	}

	// Generate self-signed wildcard certificate
	certPEM, keyPEM, err := generateSelfSignedCert(cfg.Domain)
	if err != nil {
		return fmt.Errorf("generate TLS cert: %w", err)
	}

	// Write temp files for kubectl create secret tls
	certFile, err := os.CreateTemp("", "polyon-cert-*.pem")
	if err != nil {
		return fmt.Errorf("create cert temp file: %w", err)
	}
	defer os.Remove(certFile.Name())

	keyFile, err := os.CreateTemp("", "polyon-key-*.pem")
	if err != nil {
		return fmt.Errorf("create key temp file: %w", err)
	}
	defer os.Remove(keyFile.Name())

	if _, err := certFile.Write(certPEM); err != nil {
		return fmt.Errorf("write cert: %w", err)
	}
	certFile.Close()

	if _, err := keyFile.Write(keyPEM); err != nil {
		return fmt.Errorf("write key: %w", err)
	}
	keyFile.Close()

	// Use kubectl create secret tls directly
	cmd := exec.Command("kubectl", "create", "secret", "tls", "polyon-tls",
		"--cert="+certFile.Name(),
		"--key="+keyFile.Name(),
		"-n", cfg.Namespace,
	)

	var stderr bytes.Buffer
	cmd.Stderr = &stderr

	out, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("kubectl create secret tls: %s\n%s", stderr.String(), err)
	}

	log.Printf("[K8S] %s", strings.TrimSpace(string(out)))
	return nil
}
